spring:
  application:
    name: eshop-auth
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  thymeleaf:
    cache: false
  redis:
    port: 6379
    host: 127.0.0.1
  session:
    store-type: redis

server:
  port: 20000
