spring:
  application:
    name: eshop-cart
  thymeleaf:
    cache: false
  redis:
    port: 6379
    host: 127.0.0.1
  session:
    store-type: redis

eshop:
  thread:
    coreSize: 20
    maxSize: 200
    keepAliveTime: 10

server:
  port: 30000
