server:
  port: 9999
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: eshop-search

# 打印sql
logging:
  level:
    com.hxm.eshop: debug
    com.alibaba.nacos.client.config.impl: WARN
    com.alibaba.nacos.client.naming: WARN


