spring:
  cloud:
    gateway:
      routes:
        - id: product_route
          uri: lb://eshop-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://eshop-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: ware_route
          uri: lb://eshop-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

        - id: mall_host_route # 要放在后面
          uri: lb://eshop-product
          predicates:
            - Host=eshop.com, item.eshop.com

        - id: mall_search_route
          uri: lb://eshop-search
          predicates:
            - Host=search.eshop.com

        - id: mall_auth_route
          uri: lb://eshop-auth
          predicates:
            - Host=auth.eshop.com
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  application:
    name: eshop-gateway

server:
  port: 88